---
- name: Generate the OS data code
  when: semantic_hostname_os is not defined
  set_fact:
    semantic_hostname_os: "{{ semantic_hostname_os_code }}{{ semantic_hostname_os_version }}"

- name: Set the full semantic hostname
  when: semantic_hostname is not defined
  set_fact:
    semantic_hostname: "{{ semantic_hostname_sections | join(semantic_hostname_section_delimiter) }}"

- name: Debug
  when: semantic_hostname_debug
  debug:
    var: semantic_hostname

- name: Set the hostname
  when: semantic_hostname_set
  hostname:
    name: "{{ semantic_hostname }}"

...
